name: NoAnyBoom
version: '1.0'
main: org.encinet.noAnyBoom.NoAnyBoom
api-version: 1.18
description: Allows explosive blocks and entities to be handled normally while blocking dangerous spawns and explosions.
authors: [ Noctiro ]
